### ISSUE TITLE
 After 30 epoches training corresponding to ‘’fold0_idx.npy'，the val loss is still 0.8 more or less。

### ISSUE THREAD

**Issue by 675492062** [MehrdadNoori/Attention-Guided-Version-of-2D-UNet-for-Automatic-Brain-Tumor-Segmentation#11]
After 30 epoches training corresponding to ‘’fold0_idx.npy'，the val loss is still 0.8 more or less. Is there any one facing the situation like me?

**Comment by Qiannini** [comment]
I faced the same problem as you.and I also wonder to know why?

**Comment by Qiannini** [comment]
I faced the  same problem as you and I wonder to know why?

**Comment by zhenxing123** [comment]
> 经过30个与“fold0_idx.npy”相对应的纪元训练后，val损失仍然或多或少为0.8。有没有人像我一样面对这种情况？

你好，我想问一下，问什么在数据预处理的时候会报错？
Traceback (most recent call last):
  File "E:/Pytorch Project/Brain-Tumor-Segmentation-master/prepare_data.py", line 164, in <module>
    cfg['crop_coord'], cfg['data_channels'], cfg['k_fold'])
  File "E:/Pytorch Project/Brain-Tumor-Segmentation-master/prepare_data.py", line 119, in create_table
    all_modalities, brain_affine, brain_name = read_brain(brain_dir, mode='train', **crop_coordinates)
  File "E:/Pytorch Project/Brain-Tumor-Segmentation-master/prepare_data.py", line 46, in read_brain
    modalities_dir = [flair[0], t1[0], t1ce[0], t2[0], gt[0]]
IndexError: list index out of range
Closing remaining open files:./data/data.hdf5...done
您可以帮忙解答一下吗？

**Comment by 675492062** [comment]
不是提示了数组索引越界了吗？亲！这些问题问你身边的同学更靠谱

**Comment by Xiuxiu21** [comment]
解决了吗

**Comment by Coolwen1997** [comment]
I have occurred the same problem, the results of segmentation are terrible.

**Comment by Xiuxiu21** [comment]
可以加联系方式吗？&nbsp; ***@***.***


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mehrdad-Noori/Brain-Tumor-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mehrdad-Noori/Brain-Tumor-Segmentation]  After 30 epoches training corresponding to ‘’fold0_idx.npy'，the val loss is still 0.8 more or less。 (#11)





 
I have occurred the same problem, the results of segmentation are terrible.

**Comment by Coolwen1997** [comment]
> ###
> **[Xiuxiu21](/Xiuxiu21) ** commented [Mar 13, 2023](#issuecomment-1465456059) via email

Sure. qq:394752054
